# Название workflow
name: Java CI with Maven

# Триггеры для запуска workflow
on: [push, pull_request]

# Определение задач (jobs)
jobs:
  # Задача с именем "build"
  build:
    # Указывает, что задача будет выполняться на последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги, которые будут выполнены в рамках задачи
    steps:
      # Клонирование репозитория
      - uses: actions/checkout@v2

      # Настройка JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # Версия Java
          java-version: '11'
          # Описание (необязательное поле)
          distribution: 'adopt'

      # Выполнение команды Maven
      - name: Run Maven build
        run: mvn -B -e verify
